-- MySQL Script generated by MySQL Workbench
-- 04/22/16 01:19:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uzytkownicy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`uzytkownicy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`uzytkownicy` (
  `id_uzytkownika` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `haslo` VARCHAR(32) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `imie` VARCHAR(30) NULL,
  `nazwisko` VARCHAR(30) CHARACTER SET 'utf8' NULL,
  `telefon` VARCHAR(20) NULL,
  PRIMARY KEY (`id_uzytkownika`),
  UNIQUE INDEX `id_uzytkownika_UNIQUE` (`id_uzytkownika` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rezerwacje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rezerwacje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rezerwacje` (
  `id_rezerwacji` SMALLINT(5) UNSIGNED NOT NULL,
  `data_rezerwacji` TIMESTAMP(50) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_seansu` DATE NOT NULL,
  `uzytkownicy_id_uzytkownika` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rezerwacji`, `uzytkownicy_id_uzytkownika`),
  UNIQUE INDEX `id_rezerwacje_UNIQUE` (`id_rezerwacji` ASC),
  INDEX `fk_rezerwacje_uzytkownicy_idx` (`uzytkownicy_id_uzytkownika` ASC),
  CONSTRAINT `fk_rezerwacje_uzytkownicy`
    FOREIGN KEY (`uzytkownicy_id_uzytkownika`)
    REFERENCES `mydb`.`uzytkownicy` (`id_uzytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filmy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`filmy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`filmy` (
  `id_filmu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NOT NULL,
  `filmweb_id` INT NOT NULL,
  PRIMARY KEY (`id_filmu`),
  UNIQUE INDEX `idfilmy_UNIQUE` (`id_filmu` ASC),
  UNIQUE INDEX `filmweb_id_UNIQUE` (`filmweb_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale_kinowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sale_kinowe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sale_kinowe` (
  `id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_sale_kinowe`),
  UNIQUE INDEX `id_sale_kinowe_UNIQUE` (`id_sale_kinowe` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seanse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`seanse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`seanse` (
  `id_seansu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rozpoczecie` DATETIME NOT NULL,
  `zakonczenie` DATETIME NOT NULL,
  `sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  `filmy_id_filmu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_seansu`, `sale_kinowe_id_sale_kinowe`, `filmy_id_filmu`),
  UNIQUE INDEX `idseanse_UNIQUE` (`id_seansu` ASC),
  INDEX `fk_seanse_sale_kinowe1_idx` (`sale_kinowe_id_sale_kinowe` ASC),
  INDEX `fk_seanse_filmy1_idx` (`filmy_id_filmu` ASC),
  CONSTRAINT `fk_seanse_sale_kinowe1`
    FOREIGN KEY (`sale_kinowe_id_sale_kinowe`)
    REFERENCES `mydb`.`sale_kinowe` (`id_sale_kinowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seanse_filmy1`
    FOREIGN KEY (`filmy_id_filmu`)
    REFERENCES `mydb`.`filmy` (`id_filmu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bilety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bilety` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bilety` (
  `id_biletu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(45) NOT NULL,
  `ceny_biletow_id_ceny_biletow` INT UNSIGNED NOT NULL,
  `cena` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`id_biletu`),
  UNIQUE INDEX `id_biletu_UNIQUE` (`id_biletu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`miejsca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`miejsca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`miejsca` (
  `id_miejsca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rzad` INT UNSIGNED NULL,
  `miejsce` INT UNSIGNED NULL,
  `sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  `bilety_id_biletu` INT UNSIGNED NOT NULL,
  `bilety_ceny_biletow_id_ceny_biletow` INT UNSIGNED NOT NULL,
  `rezerwacje_id_rezerwacji1` SMALLINT(5) UNSIGNED NOT NULL,
  `rezerwacje_uzytkownicy_id_uzytkownika1` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_miejsca`, `sale_kinowe_id_sale_kinowe`),
  UNIQUE INDEX `id_miejsca_UNIQUE` (`id_miejsca` ASC),
  INDEX `fk_miejsca_sale_kinowe1_idx` (`sale_kinowe_id_sale_kinowe` ASC),
  INDEX `fk_miejsca_bilety1_idx` (`bilety_id_biletu` ASC, `bilety_ceny_biletow_id_ceny_biletow` ASC),
  INDEX `fk_miejsca_rezerwacje2_idx` (`rezerwacje_id_rezerwacji1` ASC, `rezerwacje_uzytkownicy_id_uzytkownika1` ASC),
  CONSTRAINT `fk_miejsca_sale_kinowe1`
    FOREIGN KEY (`sale_kinowe_id_sale_kinowe`)
    REFERENCES `mydb`.`sale_kinowe` (`id_sale_kinowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miejsca_bilety1`
    FOREIGN KEY (`bilety_id_biletu` , `bilety_ceny_biletow_id_ceny_biletow`)
    REFERENCES `mydb`.`bilety` (`id_biletu` , `ceny_biletow_id_ceny_biletow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miejsca_rezerwacje2`
    FOREIGN KEY (`rezerwacje_id_rezerwacji1` , `rezerwacje_uzytkownicy_id_uzytkownika1`)
    REFERENCES `mydb`.`rezerwacje` (`id_rezerwacji` , `uzytkownicy_id_uzytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
