-- MySQL Script generated by MySQL Workbench
-- 04/29/16 23:55:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kino
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kino` ;

-- -----------------------------------------------------
-- Schema kino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kino` DEFAULT CHARACTER SET utf8 ;
USE `kino` ;

-- -----------------------------------------------------
-- Table `kino`.`uzytkownicy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`uzytkownicy` ;

CREATE TABLE IF NOT EXISTS `kino`.`uzytkownicy` (
  `id_uzytkownika` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `haslo` VARCHAR(32) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `imie` VARCHAR(30) NULL,
  `nazwisko` VARCHAR(30) CHARACTER SET 'utf8' NULL,
  `telefon` VARCHAR(20) NULL,
  PRIMARY KEY (`id_uzytkownika`),
  UNIQUE INDEX `id_uzytkownika_UNIQUE` (`id_uzytkownika` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kino`.`sale_kinowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`sale_kinowe` ;

CREATE TABLE IF NOT EXISTS `kino`.`sale_kinowe` (
  `id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_sale_kinowe`),
  UNIQUE INDEX `id_sale_kinowe_UNIQUE` (`id_sale_kinowe` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kino`.`filmy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`filmy` ;

CREATE TABLE IF NOT EXISTS `kino`.`filmy` (
  `id_filmu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NOT NULL,
  `filmweb_id` INT NOT NULL,
  PRIMARY KEY (`id_filmu`),
  UNIQUE INDEX `idfilmy_UNIQUE` (`id_filmu` ASC),
  UNIQUE INDEX `filmweb_id_UNIQUE` (`filmweb_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kino`.`seanse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`seanse` ;

CREATE TABLE IF NOT EXISTS `kino`.`seanse` (
  `id_seansu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rozpoczecie` DATETIME NOT NULL,
  `zakonczenie` DATETIME NOT NULL,
  `sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  `filmy_id_filmu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_seansu`, `sale_kinowe_id_sale_kinowe`, `filmy_id_filmu`),
  UNIQUE INDEX `idseanse_UNIQUE` (`id_seansu` ASC),
  INDEX `fk_seanse_sale_kinowe1_idx` (`sale_kinowe_id_sale_kinowe` ASC),
  INDEX `fk_seanse_filmy1_idx` (`filmy_id_filmu` ASC),
  CONSTRAINT `fk_seanse_sale_kinowe1`
    FOREIGN KEY (`sale_kinowe_id_sale_kinowe`)
    REFERENCES `kino`.`sale_kinowe` (`id_sale_kinowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seanse_filmy1`
    FOREIGN KEY (`filmy_id_filmu`)
    REFERENCES `kino`.`filmy` (`id_filmu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kino`.`rezerwacje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`rezerwacje` ;

CREATE TABLE IF NOT EXISTS `kino`.`rezerwacje` (
  `id_rezerwacji` SMALLINT(5) UNSIGNED NOT NULL,
  `data_rezerwacji` TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  `data_seansu` DATE NOT NULL,
  `uzytkownicy_id_uzytkownika` SMALLINT(5) UNSIGNED NOT NULL,
  `seanse_id_seansu` INT UNSIGNED NOT NULL,
  `seanse_sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  `seanse_filmy_id_filmu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rezerwacji`, `uzytkownicy_id_uzytkownika`, `seanse_id_seansu`, `seanse_sale_kinowe_id_sale_kinowe`, `seanse_filmy_id_filmu`),
  UNIQUE INDEX `id_rezerwacje_UNIQUE` (`id_rezerwacji` ASC),
  INDEX `fk_rezerwacje_uzytkownicy_idx` (`uzytkownicy_id_uzytkownika` ASC),
  INDEX `fk_rezerwacje_seanse1_idx` (`seanse_id_seansu` ASC, `seanse_sale_kinowe_id_sale_kinowe` ASC, `seanse_filmy_id_filmu` ASC),
  CONSTRAINT `fk_rezerwacje_uzytkownicy`
    FOREIGN KEY (`uzytkownicy_id_uzytkownika`)
    REFERENCES `kino`.`uzytkownicy` (`id_uzytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rezerwacje_seanse1`
    FOREIGN KEY (`seanse_id_seansu` , `seanse_sale_kinowe_id_sale_kinowe` , `seanse_filmy_id_filmu`)
    REFERENCES `kino`.`seanse` (`id_seansu` , `sale_kinowe_id_sale_kinowe` , `filmy_id_filmu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kino`.`miejsca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`miejsca` ;

CREATE TABLE IF NOT EXISTS `kino`.`miejsca` (
  `id_miejsca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rzad` INT UNSIGNED NULL,
  `miejsce` INT UNSIGNED NULL,
  `sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_miejsca`, `sale_kinowe_id_sale_kinowe`),
  UNIQUE INDEX `id_miejsca_UNIQUE` (`id_miejsca` ASC),
  INDEX `fk_miejsca_sale_kinowe1_idx` (`sale_kinowe_id_sale_kinowe` ASC),
  CONSTRAINT `fk_miejsca_sale_kinowe1`
    FOREIGN KEY (`sale_kinowe_id_sale_kinowe`)
    REFERENCES `kino`.`sale_kinowe` (`id_sale_kinowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kino`.`bilety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kino`.`bilety` ;

CREATE TABLE IF NOT EXISTS `kino`.`bilety` (
  `id_biletu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(45) NOT NULL,
  `ceny_biletow_id_ceny_biletow` INT UNSIGNED NOT NULL,
  `cena` DECIMAL(10) NOT NULL,
  `miejsca_id_miejsca` INT UNSIGNED NOT NULL,
  `miejsca_sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  `rezerwacje_id_rezerwacji` SMALLINT(5) UNSIGNED NOT NULL,
  `rezerwacje_uzytkownicy_id_uzytkownika` SMALLINT(5) UNSIGNED NOT NULL,
  `rezerwacje_seanse_id_seansu` INT UNSIGNED NOT NULL,
  `rezerwacje_seanse_sale_kinowe_id_sale_kinowe` SMALLINT(2) UNSIGNED NOT NULL,
  `rezerwacje_seanse_filmy_id_filmu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_biletu`, `miejsca_id_miejsca`, `miejsca_sale_kinowe_id_sale_kinowe`, `rezerwacje_id_rezerwacji`, `rezerwacje_uzytkownicy_id_uzytkownika`, `rezerwacje_seanse_id_seansu`, `rezerwacje_seanse_sale_kinowe_id_sale_kinowe`, `rezerwacje_seanse_filmy_id_filmu`),
  UNIQUE INDEX `id_biletu_UNIQUE` (`id_biletu` ASC),
  INDEX `fk_bilety_miejsca1_idx` (`miejsca_id_miejsca` ASC, `miejsca_sale_kinowe_id_sale_kinowe` ASC),
  INDEX `fk_bilety_rezerwacje1_idx` (`rezerwacje_id_rezerwacji` ASC, `rezerwacje_uzytkownicy_id_uzytkownika` ASC, `rezerwacje_seanse_id_seansu` ASC, `rezerwacje_seanse_sale_kinowe_id_sale_kinowe` ASC, `rezerwacje_seanse_filmy_id_filmu` ASC),
  CONSTRAINT `fk_bilety_miejsca1`
    FOREIGN KEY (`miejsca_id_miejsca` , `miejsca_sale_kinowe_id_sale_kinowe`)
    REFERENCES `kino`.`miejsca` (`id_miejsca` , `sale_kinowe_id_sale_kinowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilety_rezerwacje1`
    FOREIGN KEY (`rezerwacje_id_rezerwacji` , `rezerwacje_uzytkownicy_id_uzytkownika` , `rezerwacje_seanse_id_seansu` , `rezerwacje_seanse_sale_kinowe_id_sale_kinowe` , `rezerwacje_seanse_filmy_id_filmu`)
    REFERENCES `kino`.`rezerwacje` (`id_rezerwacji` , `uzytkownicy_id_uzytkownika` , `seanse_id_seansu` , `seanse_sale_kinowe_id_sale_kinowe` , `seanse_filmy_id_filmu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
